### ISSUE TITLE
Configuration Editor GUI

### ISSUE THREAD

**Issue by hong-meiling-2002** [TaianC/raspbot-rca#5]
Component adds GUI letting users edit configurations through an interface instead of with a text editor.
Not included in v1.2 due to the tedious process of having to add entries for each value and section.
Targeted for release in v1.2.1.

**Comment by TaianC** [comment]
The enhancement will not be put into development due to not being necessary at all (text editors work fine) and if it was put into development it would take forever to make every single UI widget in Tkinter, and there's always going to be gridding issues.
If there is an issue with the current text editor solution this will be re-explored as a Plan B. Otherwise it's staying in the waste bin.
